# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4c252bcebc7489cfc331d19121e9a24a0df20575bdac8aeaf04f3b42e035fa248a13cc3487de913c6710b48295e9b961026f7c3683551d9eb361c63d07f47c8

test:
  secret_key_base: 2364e164f771a0c59fd20173ef205e548ed7dc70b0a8ab551f33206df9076f19bd69685dc649d5a69d968cbda63aa911f77f4d3906b9ba215ae6c0c358a2d5bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
